// Code generated by Lox.GenerateAst do not update manually.
namespace Lox
{
    public abstract record Expr
    {
        public interface IVisitor<TOut>
        {
            TOut VisitAssignExpr(Assign expr);
            TOut VisitBinaryExpr(Binary expr);
            TOut VisitCallExpr(Call expr);
            TOut VisitGetExpr(Get expr);
            TOut VisitGroupingExpr(Grouping expr);
            TOut VisitLiteralExpr(Literal expr);
            TOut VisitLogicalExpr(Logical expr);
            TOut VisitSetExpr(Set expr);
            TOut VisitSuperExpr(Super expr);
            TOut VisitThisExpr(This expr);
            TOut VisitUnaryExpr(Unary expr);
            TOut VisitVariableExpr(Variable expr);
        }
        public record Assign(Token Name, Expr Value) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitAssignExpr(this);
        }
        public record Binary(Expr Left, Token Operator, Expr Right) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitBinaryExpr(this);
        }
        public record Call(Expr Callee, Token Paren, List<Expr> Arguments) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitCallExpr(this);
        }
        public record Get(Expr Obj, Token Name) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitGetExpr(this);
        }
        public record Grouping(Expr Expr) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitGroupingExpr(this);
        }
        public record Literal(object? Value) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitLiteralExpr(this);
        }
        public record Logical(Expr Left, Token Operator, Expr Right) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitLogicalExpr(this);
        }
        public record Set(Expr Obj, Token Name, Expr? Value) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitSetExpr(this);
        }
        public record Super(Token Keyword, Token Method) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitSuperExpr(this);
        }
        public record This(Token Keyword) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitThisExpr(this);
        }
        public record Unary(Token Operator, Expr Right) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitUnaryExpr(this);
        }
        public record Variable(Token Name) : Expr
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitVariableExpr(this);
        }

        public abstract TOut Accept<TOut>(IVisitor<TOut> visitor);
    }
}
