// Code generated by Lox.GenerateAst do not update manually.
namespace Lox
{
    public abstract record Stmt
    {
        public interface IVisitor<TOut>
        {
            TOut VisitBlockStmt(Block stmt);
            TOut VisitExpressionStmt(Expression stmt);
            TOut VisitPrintStmt(Print stmt);
            TOut VisitVarStmt(Var stmt);
        }
        public record Block(List<Stmt> Statements) : Stmt
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitBlockStmt(this);
        }
        public record Expression(Expr Expr) : Stmt
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitExpressionStmt(this);
        }
        public record Print(Expr Expr) : Stmt
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitPrintStmt(this);
        }
        public record Var(Token Name, Expr? Init) : Stmt
        {
            public override TOut Accept<TOut>(IVisitor<TOut> visitor) =>
                visitor.VisitVarStmt(this);
        }

        public abstract TOut Accept<TOut>(IVisitor<TOut> visitor);
    }
}
